/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PdfBinary = IDL.Vec(IDL.Nat8);
export const PdfMetadata = IDL.Record({ 'uploadTimestamp' : IDL.Nat64 });
export const Room = IDL.Text;
export const PdfEntry = IDL.Record({
  'pdf' : PdfBinary,
  'metadata' : PdfMetadata,
  'room' : Room,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DropboxToken = IDL.Text;
export const MetadataAndPdf = IDL.Record({
  'pdf' : PdfBinary,
  'metadata' : PdfMetadata,
});
export const UploadResult = IDL.Variant({
  'error' : IDL.Text,
  'success' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllSortedByRoom' : IDL.Func([], [IDL.Vec(PdfEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDropboxToken' : IDL.Func([], [IDL.Opt(DropboxToken)], ['query']),
  'getPdf' : IDL.Func([Room], [MetadataAndPdf], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setDropboxToken' : IDL.Func([DropboxToken], [], []),
  'uploadPdf' : IDL.Func([Room, PdfBinary, IDL.Nat64], [UploadResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PdfBinary = IDL.Vec(IDL.Nat8);
  const PdfMetadata = IDL.Record({ 'uploadTimestamp' : IDL.Nat64 });
  const Room = IDL.Text;
  const PdfEntry = IDL.Record({
    'pdf' : PdfBinary,
    'metadata' : PdfMetadata,
    'room' : Room,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DropboxToken = IDL.Text;
  const MetadataAndPdf = IDL.Record({
    'pdf' : PdfBinary,
    'metadata' : PdfMetadata,
  });
  const UploadResult = IDL.Variant({
    'error' : IDL.Text,
    'success' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllSortedByRoom' : IDL.Func([], [IDL.Vec(PdfEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDropboxToken' : IDL.Func([], [IDL.Opt(DropboxToken)], ['query']),
    'getPdf' : IDL.Func([Room], [MetadataAndPdf], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setDropboxToken' : IDL.Func([DropboxToken], [], []),
    'uploadPdf' : IDL.Func([Room, PdfBinary, IDL.Nat64], [UploadResult], []),
  });
};

export const init = ({ IDL }) => { return []; };