/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BinaryField {
  'id' : string,
  'value' : FieldValue,
  'description' : string,
}
export interface ChecklistSection {
  'id' : string,
  'description' : string,
  'binaryFields' : Array<BinaryField>,
  'yesNoFields' : Array<YesNoField>,
  'textFields' : Array<TextField>,
}
export type DropboxToken = string;
export type FieldValue = { 'no' : null } |
  { 'yes' : null } |
  { 'noAnswer' : null } |
  { 'notAppicable' : null } |
  { 'text' : string } |
  { 'notTested' : null };
export interface MetadataAndPdf { 'pdf' : PdfBinary, 'metadata' : PdfMetadata }
export type PdfBinary = Uint8Array;
export interface PdfEntry {
  'pdf' : PdfBinary,
  'metadata' : PdfMetadata,
  'room' : Room,
}
export interface PdfMetadata { 'uploadTimestamp' : bigint }
export type Room = string;
export interface RoomChecklist { 'checklistSections' : Array<ChecklistSection> }
export interface TextField {
  'id' : string,
  'value' : FieldValue,
  'description' : string,
}
export type UploadResult = { 'error' : string } |
  { 'success' : string };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface YesNoField {
  'id' : string,
  'value' : FieldValue,
  'description' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'areAdminPrivilegesAvailable' : ActorMethod<[], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimAdminPrivileges' : ActorMethod<[], undefined>,
  'getAllSortedByRoom' : ActorMethod<[], Array<PdfEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDropboxToken' : ActorMethod<[], [] | [DropboxToken]>,
  'getPdf' : ActorMethod<[Room], MetadataAndPdf>,
  'getRoomChecklist' : ActorMethod<[Room], [] | [RoomChecklist]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveRoomChecklist' : ActorMethod<[Room, RoomChecklist], UploadResult>,
  'setDropboxToken' : ActorMethod<[DropboxToken], undefined>,
  'uploadPdf' : ActorMethod<[Room, PdfBinary, bigint], UploadResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];