/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type PdfBinary = Uint8Array;
export interface ChecklistSection {
    id: string;
    description: string;
    binaryFields: Array<BinaryField>;
    yesNoFields: Array<YesNoField>;
    textFields: Array<TextField>;
}
export interface PdfMetadata {
    uploadTimestamp: bigint;
}
export type FieldValue = {
    __kind__: "no";
    no: null;
} | {
    __kind__: "yes";
    yes: null;
} | {
    __kind__: "noAnswer";
    noAnswer: null;
} | {
    __kind__: "notAppicable";
    notAppicable: null;
} | {
    __kind__: "text";
    text: string;
} | {
    __kind__: "notTested";
    notTested: null;
};
export type Room = string;
export type UploadResult = {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: string;
};
export interface YesNoField {
    id: string;
    value: FieldValue;
    description: string;
}
export interface RoomChecklist {
    checklistSections: Array<ChecklistSection>;
}
export type DropboxToken = string;
export interface PdfEntry {
    pdf: PdfBinary;
    metadata: PdfMetadata;
    room: Room;
}
export interface BinaryField {
    id: string;
    value: FieldValue;
    description: string;
}
export interface TextField {
    id: string;
    value: FieldValue;
    description: string;
}
export interface MetadataAndPdf {
    pdf: PdfBinary;
    metadata: PdfMetadata;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    areAdminPrivilegesAvailable(): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    claimAdminPrivileges(): Promise<void>;
    getAllSortedByRoom(): Promise<Array<PdfEntry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDropboxToken(): Promise<DropboxToken | null>;
    getPdf(room: Room): Promise<MetadataAndPdf>;
    getRoomChecklist(room: Room): Promise<RoomChecklist | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveRoomChecklist(_room: Room, _checklist: RoomChecklist): Promise<UploadResult>;
    setDropboxToken(token: DropboxToken): Promise<void>;
    uploadPdf(_room: Room, _pdf: PdfBinary, _timestamp: bigint): Promise<UploadResult>;
}
import type { BinaryField as _BinaryField, ChecklistSection as _ChecklistSection, DropboxToken as _DropboxToken, FieldValue as _FieldValue, RoomChecklist as _RoomChecklist, TextField as _TextField, UploadResult as _UploadResult, UserProfile as _UserProfile, UserRole as _UserRole, YesNoField as _YesNoField } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async areAdminPrivilegesAvailable(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.areAdminPrivilegesAvailable();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.areAdminPrivilegesAvailable();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async claimAdminPrivileges(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.claimAdminPrivileges();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimAdminPrivileges();
            return result;
        }
    }
    async getAllSortedByRoom(): Promise<Array<PdfEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSortedByRoom();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSortedByRoom();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDropboxToken(): Promise<DropboxToken | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDropboxToken();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDropboxToken();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPdf(arg0: Room): Promise<MetadataAndPdf> {
        if (this.processError) {
            try {
                const result = await this.actor.getPdf(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPdf(arg0);
            return result;
        }
    }
    async getRoomChecklist(arg0: Room): Promise<RoomChecklist | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomChecklist(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomChecklist(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveRoomChecklist(arg0: Room, arg1: RoomChecklist): Promise<UploadResult> {
        if (this.processError) {
            try {
                const result = await this.actor.saveRoomChecklist(arg0, to_candid_RoomChecklist_n22(this._uploadFile, this._downloadFile, arg1));
                return from_candid_UploadResult_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveRoomChecklist(arg0, to_candid_RoomChecklist_n22(this._uploadFile, this._downloadFile, arg1));
            return from_candid_UploadResult_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async setDropboxToken(arg0: DropboxToken): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDropboxToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDropboxToken(arg0);
            return result;
        }
    }
    async uploadPdf(arg0: Room, arg1: PdfBinary, arg2: bigint): Promise<UploadResult> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPdf(arg0, arg1, arg2);
                return from_candid_UploadResult_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPdf(arg0, arg1, arg2);
            return from_candid_UploadResult_n36(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BinaryField_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BinaryField): BinaryField {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ChecklistSection_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChecklistSection): ChecklistSection {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_FieldValue_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FieldValue): FieldValue {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_RoomChecklist_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomChecklist): RoomChecklist {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TextField_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TextField): TextField {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UploadResult_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UploadResult): UploadResult {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_YesNoField_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _YesNoField): YesNoField {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DropboxToken]): DropboxToken | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RoomChecklist]): RoomChecklist | null {
    return value.length === 0 ? null : from_candid_RoomChecklist_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    description: string;
    binaryFields: Array<_BinaryField>;
    yesNoFields: Array<_YesNoField>;
    textFields: Array<_TextField>;
}): {
    id: string;
    description: string;
    binaryFields: Array<BinaryField>;
    yesNoFields: Array<YesNoField>;
    textFields: Array<TextField>;
} {
    return {
        id: value.id,
        description: value.description,
        binaryFields: from_candid_vec_n13(_uploadFile, _downloadFile, value.binaryFields),
        yesNoFields: from_candid_vec_n18(_uploadFile, _downloadFile, value.yesNoFields),
        textFields: from_candid_vec_n20(_uploadFile, _downloadFile, value.textFields)
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    value: _FieldValue;
    description: string;
}): {
    id: string;
    value: FieldValue;
    description: string;
} {
    return {
        id: value.id,
        value: from_candid_FieldValue_n16(_uploadFile, _downloadFile, value.value),
        description: value.description
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    checklistSections: Array<_ChecklistSection>;
}): {
    checklistSections: Array<ChecklistSection>;
} {
    return {
        checklistSections: from_candid_vec_n10(_uploadFile, _downloadFile, value.checklistSections)
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    no: null;
} | {
    yes: null;
} | {
    noAnswer: null;
} | {
    notAppicable: null;
} | {
    text: string;
} | {
    notTested: null;
}): {
    __kind__: "no";
    no: null;
} | {
    __kind__: "yes";
    yes: null;
} | {
    __kind__: "noAnswer";
    noAnswer: null;
} | {
    __kind__: "notAppicable";
    notAppicable: null;
} | {
    __kind__: "text";
    text: string;
} | {
    __kind__: "notTested";
    notTested: null;
} {
    return "no" in value ? {
        __kind__: "no",
        no: value.no
    } : "yes" in value ? {
        __kind__: "yes",
        yes: value.yes
    } : "noAnswer" in value ? {
        __kind__: "noAnswer",
        noAnswer: value.noAnswer
    } : "notAppicable" in value ? {
        __kind__: "notAppicable",
        notAppicable: value.notAppicable
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : "notTested" in value ? {
        __kind__: "notTested",
        notTested: value.notTested
    } : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: string;
} | {
    success: string;
}): {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: string;
} {
    return "error" in value ? {
        __kind__: "error",
        error: value.error
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChecklistSection>): Array<ChecklistSection> {
    return value.map((x)=>from_candid_ChecklistSection_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BinaryField>): Array<BinaryField> {
    return value.map((x)=>from_candid_BinaryField_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_YesNoField>): Array<YesNoField> {
    return value.map((x)=>from_candid_YesNoField_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TextField>): Array<TextField> {
    return value.map((x)=>from_candid_TextField_n21(_uploadFile, _downloadFile, x));
}
function to_candid_BinaryField_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BinaryField): _BinaryField {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_ChecklistSection_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChecklistSection): _ChecklistSection {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_FieldValue_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FieldValue): _FieldValue {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_RoomChecklist_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomChecklist): _RoomChecklist {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_TextField_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TextField): _TextField {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_YesNoField_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: YesNoField): _YesNoField {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    checklistSections: Array<ChecklistSection>;
}): {
    checklistSections: Array<_ChecklistSection>;
} {
    return {
        checklistSections: to_candid_vec_n24(_uploadFile, _downloadFile, value.checklistSections)
    };
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    description: string;
    binaryFields: Array<BinaryField>;
    yesNoFields: Array<YesNoField>;
    textFields: Array<TextField>;
}): {
    id: string;
    description: string;
    binaryFields: Array<_BinaryField>;
    yesNoFields: Array<_YesNoField>;
    textFields: Array<_TextField>;
} {
    return {
        id: value.id,
        description: value.description,
        binaryFields: to_candid_vec_n27(_uploadFile, _downloadFile, value.binaryFields),
        yesNoFields: to_candid_vec_n32(_uploadFile, _downloadFile, value.yesNoFields),
        textFields: to_candid_vec_n34(_uploadFile, _downloadFile, value.textFields)
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    value: FieldValue;
    description: string;
}): {
    id: string;
    value: _FieldValue;
    description: string;
} {
    return {
        id: value.id,
        value: to_candid_FieldValue_n30(_uploadFile, _downloadFile, value.value),
        description: value.description
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "no";
    no: null;
} | {
    __kind__: "yes";
    yes: null;
} | {
    __kind__: "noAnswer";
    noAnswer: null;
} | {
    __kind__: "notAppicable";
    notAppicable: null;
} | {
    __kind__: "text";
    text: string;
} | {
    __kind__: "notTested";
    notTested: null;
}): {
    no: null;
} | {
    yes: null;
} | {
    noAnswer: null;
} | {
    notAppicable: null;
} | {
    text: string;
} | {
    notTested: null;
} {
    return value.__kind__ === "no" ? {
        no: value.no
    } : value.__kind__ === "yes" ? {
        yes: value.yes
    } : value.__kind__ === "noAnswer" ? {
        noAnswer: value.noAnswer
    } : value.__kind__ === "notAppicable" ? {
        notAppicable: value.notAppicable
    } : value.__kind__ === "text" ? {
        text: value.text
    } : value.__kind__ === "notTested" ? {
        notTested: value.notTested
    } : value;
}
function to_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ChecklistSection>): Array<_ChecklistSection> {
    return value.map((x)=>to_candid_ChecklistSection_n25(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<BinaryField>): Array<_BinaryField> {
    return value.map((x)=>to_candid_BinaryField_n28(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<YesNoField>): Array<_YesNoField> {
    return value.map((x)=>to_candid_YesNoField_n33(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TextField>): Array<_TextField> {
    return value.map((x)=>to_candid_TextField_n35(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
